// Common
export const SEND_MAIL = 'SEND_MAIL'
export const REDIRECT = 'REDIRECT'

// Blog
export const BLOG_PAGE_LOADED = 'BLOG_PAGE_LOADED'
export const SET_PAGE = 'SET_PAGE'
export const BLOG_PAGE_UNLOADED = 'BLOG_PAGE_UNLOADED'

// Gallery
export const GALLERY_PAGE_LOADED = 'GALLERY_PAGE_LOADED'
export const GALLERY_PAGE_UNLOADED = 'GALLERY_PAGE_UNLOADED'

// About
export const UPDATE_FIELD_ABOUT = 'UPDATE_FIELD_ABOUT'
export const ASYNC_START = 'ASYNC_START'
export const ABOUT_PAGE_UNLOADED = 'ABOUT_PAGE_UNLOADED'
